CREATE DATABASE SEI;

USE SEI;

CREATE TABLE PAISES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    continente VARCHAR(100) NOT NULL
);

CREATE TABLE LOCAL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    estado VARCHAR(100) NOT NULL,
    celular VARCHAR(15)
);


CREATE TABLE ATIVIDADES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    duracao TIME NOT NULL
);


CREATE TABLE IMIGRANTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    celular VARCHAR(15) NOT NULL,
    genero ENUM('Masculino', 'Feminino', 'Outro') NOT NULL,
    pais INT NOT NULL,
    email_login VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    FOREIGN KEY (pais) REFERENCES PAISES(id)
);


CREATE TABLE EVENTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pais INT NOT NULL,
    local INT NOT NULL,
    data DATE NOT NULL,
    hora TIME NOT NULL,
    atividade INT NOT NULL,
    cep VARCHAR(10),
    observacao TEXT,
    FOREIGN KEY (pais) REFERENCES PAISES(id),
    FOREIGN KEY (local) REFERENCES LOCAL(id),
    FOREIGN KEY (atividade) REFERENCES ATIVIDADES(id)
);


CREATE TABLE ENCONTRO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    imigrante INT NOT NULL,
    evento INT NOT NULL,
    FOREIGN KEY (imigrante) REFERENCES IMIGRANTE(id),
    FOREIGN KEY (evento) REFERENCES EVENTO(id)
);
